---    
labels:
  i18ns:
    - i18nId: REQUIRED_PARAMETER
      values:
        - locale: ko
          value: 필수 파라미터가 누락되었습니다.
        - locale: en
          value: Missing required parameters.
    - i18nId: ENTITY_NOT_FOUND
      values:
        - locale: ko
          value: 존재하지 않는 엔티티입니다.
        - locale: en
          value: Entity does not exist.
    - i18nId: ILLEGAL_ACCESS
      values:
        - locale: ko
          value: 잘못된 접근입니다.
        - locale: en
          value: Illegal access.
    - i18nId: PASSWORD_NOT_MATCHED
      values:
        - locale: ko
          value: 비밀번호가 일치하지 않습니다.
        - locale: en
          value: Password do not matched.
    - i18nId: LOGIN_INVALID_MEMBER
      values:
        - locale: ko
          value: 유효하지 않은 사용자이거나 비밀번호입니다.
        - locale: en
          value: Invalid Member or Member password.
    - i18nId: ACCESS_TOKEN_INVALID
      values:
        - locale: ko
          value: 유효하지 않은 Access token입니다.
        - locale: en
          value: Invalid Access token.
    - i18nId: ACCESS_TOKEN_EXPIRED
      values:
        - locale: ko
          value: Access token이 만료되었습니다.
        - locale: en
          value: Access token has been expired.
    - i18nId: MEMBER_DUPLICATED_ID
      values:
        - locale: ko
          value: 중복된 사용자 아이디입니다.
        - locale: en
          value: Duplicated Member ID.
    - i18nId: MEMBER_AVAILABLE_ID
      values:
        - locale: ko
          value: 사용 가능한 아이디입니다.
        - locale: en
          value: Avaliable Member ID.
    - i18nId: EXCEPTION_UNSUPPORTED_LOCALE
      values:
        - locale: ko
          value: 지원하지 않는 Locale 입니다.
        - locale: en
          value: Locale not supported.
    - i18nId: MESSAGE_NOT_FOUND
      values:
        - locale: ko
          value: 메시지가 존재하지 않습니다.
        - locale: en
          value: Message not found,
    - i18nId: RESPONSE_SUCCESS
      values:
        - locale: ko
          value: 요청이 정상적으로 처리되었습니다.
        - locale: en
          value: Request was successfully proceed.
    - i18nId: ILLEGAL_STATUS
      values:
        - locale: ko
          value: Entity의 상태가 이상합니다.
        - locale: en
          value: Illegal status of entity.
    - i18nId: PASSWORD_INVALID
      values:
        - locale: ko
          value: 비밀번호는 최소 8자리 이상이며 숫자, 문자, 특수문자를 최소 1개 이상 포함해야합니다.
        - locale: en
          value: The password must be at least 8 digits long and contain at least one number, letters, and special characters.
    - i18nId: LOGIN_TITLE
      values:
        - locale: ko
          value: 로그인
        - locale: en
          value: Login
    - i18nId: LOGIN_ID
      values:
        - locale: ko
          value: 아이디
        - locale: en
          value: ID
    - i18nId: LOGIN_PASSWORD
      values:
        - locale: ko
          value: 비밀번호
        - locale: en
          value: Password
    - i18nId: LOGIN_SIGN_IN
      values:
        - locale: ko
          value: 로그인
        - locale: en
          value: Login
    - i18nId: LOGIN_REGISTER
      values:
        - locale: ko
          value: 회원가입
        - locale: en
          value: Sign Up
    - i18nId: SIGN_UP_TITLE
      values:
        - locale: ko
          value: 회원가입
        - locale: en
          value: Sign Up
    - i18nId: SIGN_UP_ID
      values:
        - locale: ko
          value: 아이디
        - locale: en
          value: ID
    - i18nId: SIGN_UP_PASSWORD
      values:
        - locale: ko
          value: 비밀번호
        - locale: en
          value: Password
    - i18nId: SIGN_UP_PASSWORD_CONFIRM
      values:
        - locale: ko
          value: 비밀번호 확인
        - locale: en
          value: Password Confirm
    - i18nId: BOARD_TITLE
      values:
        - locale: ko
          value: 게시판
        - locale: en
          value: Board
    - i18nId: BOARD_SUBJECT
      values:
        - locale: ko
          value: 제목
        - locale: en
          value: Subject
    - i18nId: BOARD_CONTENT
      values:
        - locale: ko
          value: 내용
        - locale: en
          value: Content
    - i18nId: BOARD_DATE
      values:
        - locale: ko
          value: 날짜
        - locale: en
          value: Date
    - i18nId: BOARD_DELETE
      values:
        - locale: ko
          value: 삭제
        - locale: en
          value: Delete
    - i18nId: BORAD_CREATE
      values:
        - locale: ko
          value: 생성
        - locale: en
          value: Create
    - i18nId: BOARD_LOGOUT
      values:
        - locale: ko
          value: 로그아웃
        - locale: en
          value: Logout
    - i18nId: DELETE_TITLE
      values:
        - locale: ko
          value: 게시물 삭제
        - locale: en
          value: Post delete.
    - i18nId: DELETE_CONTENT
      values:
        - locale: ko
          value: 게시물을 삭제하시겠습니까?
        - locale: en
          value: Delete the Post?
    - i18nId: BUTTON_CANCEL
      values:
        - locale: ko
          value: 취소
        - locale: en
          value: Cancel
    - i18nId: BUTTON_CREATE
      values:
        - locale: ko
          value: 생성
        - locale: en
          value: Create
    - i18nId: BUTTON_DELETE
      values:
        - locale: ko
          value: 삭제
        - locale: en
          value: Delete
    - i18nId: BUTTON_SAVE
      values:
        - locale: ko
          value: 저장
        - locale: en
          value: Save
    - i18nId: BUTTON_CLOSE
      values:
        - locale: ko
          value: 닫기
        - locale: en
          value: Close
    - i18nId: WARNING_VALUE
      values:
        - locale: ko
          value: 값을 입력하세요.
        - locale: en
          value: Pleaseenter a vaue.
    - i18nId: WARNING_CONTENT
      values:
        - locale: ko
          value: 내용을 입력하세요.
        - locale: en
          value: Please enter the contents.
    - i18nId: WARNING_COMPLETE
      values:
        - locale: ko
          value: 값이 올바르지 않습니다.
        - locale: en
          value: The value is not valid.
    - i18nId: WARNING_COLLECT
      values:
        - locale: ko
          value: 두 패스워드가 일치하지 않습니다.
        - locale: en
          value: The two passwords do not match.
          